// common
export const FORM_SUBMIT_START = 'FORM_SUBMIT_START';
export const FORM_SUBMIT_FAIL = 'FORM_SUBMIT_FAIL';
export const FORM_SUBMIT_SUCCESS = 'FORM_SUBMIT_SUCCESS';

// blogs
export const LOAD_INIT_BLOGS_SUCCESS = 'LOAD_INIT_BLOGS_SUCCESS';
export const BLOG_SEARCH_SUCCESS = 'BLOG_SEARCH_SUCCESS';
export const LOAD_MY_BLOGS_SUCCESS = 'LOAD_MY_BLOGS_SUCCESS';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const LOAD_ABOUT_SUCCESS = 'LOAD_ABOUT_SUCCESS';

// Autherntication
export const SUBMIT_SIGN_IN_SUCCESS = 'SUBMIT_SIGN_IN_SUCCESS';
export const SUBMIT_EMAIL_SUCCESS = 'SUBMIT_EMAIL_SUCCESS';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const LOG_OUT = 'LOG_OUT';

export const SHOW_NAVIGATION_CLICK = 'SHOW_NAVIGATION_CLICK';
export const SHOW_SIGN_IN_CLICK = 'SHOW_SIGN_IN_CLICK';
export const SHOW_SIGN_UP_CLICK = 'SHOW_SIGN_UP_CLICK';
export const SHOW_FORGOT_PASSWORD_CLICK = 'SHOW_FORGOT_PASSWORD_CLICK';
export const CLOSE_MODAL_CLICK = 'CLOSE_MODAL_CLICK';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';

// new blog

export const DELETE_BLOGS_SUCCESS = 'DELETE_BLOGS_SUCCESS';
export const GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS';
export const UPDATE_BLOG_SUCCESS = 'UPDATE_BLOG_SUCCESS';
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS';
export const REMOVE_COMMENT_SUCCESS = 'REMOVE_COMMENT_SUCCESS';
export const UPDATE_LIKE_SUCCESS = 'UPDATE_LIKE_SUCCESS';
export const REMOVE_LIKE_SUCCESS = 'REMOVE_LIKE_SUCCESS';


// settings (user and about)

export const SETTING_LOAD_SUCCESS = 'SETTING_LOAD_SUCCESS';
export const UPDATE_ABOUT_SUCCESS = 'UPDATE_ABOUT_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';